## Here I use doSNOW to perform parallel computing
## Put this file and GoM_spectra.R into the same folder
install.packages(setdiff(c("doSNOW","tictoc"), rownames(installed.packages())))
library(doSNOW)
source("GoM_spectra.R")
## gtools is used to generate dirichlet distribution, other package is the same
library(gtools)
## tictoc is used to monitor the time into the same format
library(tictoc)
library(sirt)

## parallel computing parameters
numCores = 20L # depend on the number of cores in the server, too large may encounter RAM issues (large matrix)
cl = makeCluster(numCores)
registerDoSNOW(cl)

## given values
# K.all = c(3,8)
# N.all = c(200,500,1000,2000,5000)
# J = N/10, W = N/20
m = 100 #parallel experiments

## each row of Pi is generated by Dirichlet(1,1,...,1)
pi_gen <- function(pi,K){
  pi = rdirichlet(1,rep(1,K))
  return(pi)
}

# return mean absolute difference of Pi and Theta, as well as running time for JML, Null and Covariate-assisted
GoM_simulate <- function(A,X,K,Pi,Theta){
  ## JML
  tic()
  jml.est = gom.jml(data.frame(A),K)
  jml.time = toc()
  jml.time = jml.time$toc-jml.time$tic
  Pi.jml = as.matrix(jml.est$g)
  Theta.jml = as.matrix(jml.est$lambda[,3:(K+2)])
  idx.jml = find_best_idx(K,Pi.jml,Pi)
  pi.err.jml = mean(abs(Pi.jml[,idx.jml]-Pi))
  theta.err.jml = mean(abs(Theta.jml[,idx.jml]-Theta))
  
  ## Null
  tic()
  null.est = gom.svd(A,K)
  svd.time = toc()
  svd.time = svd.time$toc-svd.time$tic
  idx.null = find_best_idx(K,null.est$Pi,Pi)
  pi.err.svd = mean(abs(null.est$Pi[,idx.null]-Pi))
  theta.err.svd = mean(abs(null.est$Theta[,idx.null]-Theta))
  
  ## Deleted Version
  tic()
  del.est = gom.cov(A,X,K,0) # actually longer version, X don't need to calculate
  del.time = toc()
  del.time = del.time$toc-del.time$tic
  idx.del = find_best_idx(K,del.est$Pi,Pi)
  pi.err.del = mean(abs(del.est$Pi[,idx.del]-Pi))
  theta.err.del = mean(abs(del.est$Theta[,idx.del]-Theta))
  
  ## Covariate-assisted include the time of finding alpha
  ## the tuning params are all set as follows
  alpha_seq = seq(from=0,to=1,length=100)
  tic()
  alpha = find_best_alpha(alpha_seq,A,X,K)
  cov.est = gom.cov(A,X,K,alpha)
  cov.time = toc()
  cov.time = cov.time$toc-cov.time$tic
  idx.cov = find_best_idx(K,cov.est$Pi,Pi)
  pi.err.cov = mean(abs(cov.est$Pi[,idx.cov]-Pi))
  theta.err.cov = mean(abs(cov.est$Theta[,idx.null]-Theta))
  
  res = list(jml.pi=pi.err.jml, jml.theta=theta.err.jml, jml.time=jml.time,
             svd.pi=pi.err.svd, svd.theta=theta.err.svd, svd.time=svd.time,
             cov.pi=pi.err.cov, cov.theta=theta.err.cov, cov.time=cov.time,
             del.pi=pi.err.del, del.theta=theta.err.del, del.time=del.time,
             alpha=alpha)
  # alpha is also returned to check if the range is good enough
  return(res)
}

# N=200,K=3 Simulation
res_N200_K3 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 200
  K = 3
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=500,K=3 Simulation
res_N500_K3 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 500
  K = 3
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=1000,K=3 Simulation
res_N1000_K3 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 1000
  K = 3
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=2000,K=3 Simulation
res_N2000_K3 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 2000
  K = 3
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=5000,K=3 Simulation
res_N5000_K3 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 5000
  K = 3
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=200,K=8 Simulation
res_N200_K8 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 200
  K = 8
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=500,K=8 Simulation
res_N500_K8 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 500
  K = 8
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=1000,K=8 Simulation
res_N1000_K8 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 1000
  K = 8
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=2000,K=8 Simulation
res_N2000_K8 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 2000
  K = 8
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=5000,K=8 Simulation
res_N5000_K8 = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 5000
  K = 8
  J = N/10
  W = N/20
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

## Long J scenario
## J = 10N, W = 5N

# N=200,K=3 Simulation
res_N200_K3_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 200
  K = 3
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=500,K=3 Simulation
res_N500_K3_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 500
  K = 3
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=1000,K=3 Simulation
res_N1000_K3_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 1000
  K = 3
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=2000,K=3 Simulation
res_N2000_K3_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 2000
  K = 3
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=5000,K=3 Simulation
res_N5000_K3_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 5000
  K = 3
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=200,K=8 Simulation
res_N200_K8_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 200
  K = 8
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=500,K=8 Simulation
res_N500_K8_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 500
  K = 8
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=1000,K=8 Simulation
res_N1000_K8_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 1000
  K = 8
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=2000,K=8 Simulation
res_N2000_K8_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 2000
  K = 8
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

# N=5000,K=8 Simulation
res_N5000_K8_long = foreach(i=1:m,.combine=rbind,.packages = c("sirt","gtools","tictoc")) %dopar% {
  set.seed(i)
  N = 5000
  K = 8
  J = N*10
  W = N*5
  
  # generate values
  Pi = matrix(rep(0,N*K),nrow=N)
  Pi = t(apply(Pi,1,pi_gen,K=K))
  Theta = matrix(runif(J*K),ncol=K)
  M = matrix(rnorm(W*K,0,1),nrow=W)
  Pi[1:K,] = diag(rep(1,K))
  
  A_t = Pi%*%t(Theta)
  X_t = Pi%*%t(M)
  
  A = matrix(rbinom(N*J,1,A_t),nrow = N)
  X = X_t + matrix(rnorm(N*W,0,.5),nrow=N)
  X = apply(X,2,scale)
  
  res = GoM_simulate(A,X,K,Pi,Theta)
  return(res)
}

save.image("GoM_simulation.RData")
